/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.weatherdatadisplay.view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import com.mycompany.weatherdatadisplay.model.TempoModel;
import com.mycompany.weatherdatadisplay.presenter.TempoPresenter;


/**
 *
 * @author Lucas Marques Fonseca - 2018205014
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private TempoPresenter tempoPresenter;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(TempoPresenter presenter) {
        initComponents();
        tempoPresenter = presenter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dadosTempo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        incluirDados = new javax.swing.JButton();
        temperaturaDadosTempo = new javax.swing.JTextField();
        umidadeDadosTempo = new javax.swing.JTextField();
        pressaoDadosTempo = new javax.swing.JTextField();
        dataDadosTempo = new javax.swing.JFormattedTextField();
        dadosMedios = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        temperaturaMedia = new javax.swing.JLabel();
        umidadeMedia = new javax.swing.JLabel();
        pressaoMedia = new javax.swing.JLabel();
        numeroDeRegistrosPeriodo = new javax.swing.JLabel();
        selecionadorPeriodo = new javax.swing.JComboBox<>();
        configuracaoSistema = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        salvarConfig = new javax.swing.JButton();
        configSistemaLog = new javax.swing.JComboBox<>();
        ultimaAtt = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ultimaData = new javax.swing.JLabel();
        ultimaTemperatura = new javax.swing.JLabel();
        ultimaUmidade = new javax.swing.JLabel();
        ultimaPressao = new javax.swing.JLabel();
        tableRegistros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        registroTabela = new javax.swing.JTable();
        removerBotao = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        totalDeRegistros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setBackground(new java.awt.Color(204, 153, 0));
        title.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Weather Data Display");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dadosTempo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Dados do Tempo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel3.setText("Data");

        jLabel4.setText("Temperatura");

        jLabel5.setText("Umidade");

        jLabel6.setText("Pressão");

        incluirDados.setText("Incluir");
        incluirDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirDadosActionPerformed(evt);
            }
        });

        umidadeDadosTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umidadeDadosTempoActionPerformed(evt);
            }
        });

        try {
            dataDadosTempo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataDadosTempo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dataDadosTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDadosTempoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosTempoLayout = new javax.swing.GroupLayout(dadosTempo);
        dadosTempo.setLayout(dadosTempoLayout);
        dadosTempoLayout.setHorizontalGroup(
            dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosTempoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosTempoLayout.createSequentialGroup()
                        .addComponent(pressaoDadosTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dadosTempoLayout.createSequentialGroup()
                        .addGroup(dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(temperaturaDadosTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(umidadeDadosTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(dataDadosTempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(44, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosTempoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(incluirDados, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dadosTempoLayout.setVerticalGroup(
            dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosTempoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dataDadosTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(temperaturaDadosTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(umidadeDadosTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(dadosTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pressaoDadosTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(incluirDados)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        dadosMedios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(204, 153, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Dados Médios");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setText("Periodo");

        jLabel9.setText("Temperatura");

        jLabel10.setText("Umidade");

        jLabel11.setText("Pressão");

        jLabel12.setText("Número de Registros");

        temperaturaMedia.setText("Sem dados");

        umidadeMedia.setText("Sem dados");

        pressaoMedia.setText("Sem dados");

        numeroDeRegistrosPeriodo.setText("Sem dados");

        selecionadorPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diária", "Semanal", "Mensal" }));
        selecionadorPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionadorPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosMediosLayout = new javax.swing.GroupLayout(dadosMedios);
        dadosMedios.setLayout(dadosMediosLayout);
        dadosMediosLayout.setHorizontalGroup(
            dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dadosMediosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosMediosLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(selecionadorPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosMediosLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroDeRegistrosPeriodo))
                    .addGroup(dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dadosMediosLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pressaoMedia))
                        .addGroup(dadosMediosLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(umidadeMedia))
                        .addGroup(dadosMediosLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(temperaturaMedia))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        dadosMediosLayout.setVerticalGroup(
            dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosMediosLayout.createSequentialGroup()
                .addGroup(dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dadosMediosLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(selecionadorPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(temperaturaMedia))
                        .addGap(18, 18, 18)
                        .addGroup(dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(umidadeMedia)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(pressaoMedia))
                        .addGap(50, 50, 50))
                    .addGroup(dadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeroDeRegistrosPeriodo)))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        configuracaoSistema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(204, 153, 0));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Configuração do Sistema");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Log");

        salvarConfig.setText("Salvar");
        salvarConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarConfigActionPerformed(evt);
            }
        });

        configSistemaLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JSON", "XML", " " }));

        javax.swing.GroupLayout configuracaoSistemaLayout = new javax.swing.GroupLayout(configuracaoSistema);
        configuracaoSistema.setLayout(configuracaoSistemaLayout);
        configuracaoSistemaLayout.setHorizontalGroup(
            configuracaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(configuracaoSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configuracaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configuracaoSistemaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configuracaoSistemaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvarConfig)))
                .addContainerGap())
            .addGroup(configuracaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(configuracaoSistemaLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(configSistemaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );
        configuracaoSistemaLayout.setVerticalGroup(
            configuracaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configuracaoSistemaLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(salvarConfig)
                .addContainerGap())
            .addGroup(configuracaoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(configuracaoSistemaLayout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(configSistemaLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        ultimaAtt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel6.setBackground(new java.awt.Color(204, 153, 0));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Ultima atualização do tempo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel20.setText("Data");

        jLabel21.setText("Temperatura");

        jLabel22.setText("Umidade");

        jLabel23.setText("Pressão");

        ultimaData.setText("Sem dados");

        ultimaTemperatura.setText("Sem dados");

        ultimaUmidade.setText("Sem dados");

        ultimaPressao.setText("Sem dados");

        javax.swing.GroupLayout ultimaAttLayout = new javax.swing.GroupLayout(ultimaAtt);
        ultimaAtt.setLayout(ultimaAttLayout);
        ultimaAttLayout.setHorizontalGroup(
            ultimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ultimaAttLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ultimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ultimaAttLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(59, 59, 59)
                        .addComponent(ultimaData))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ultimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ultimaAttLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ultimaPressao))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ultimaAttLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ultimaUmidade))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ultimaAttLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(ultimaTemperatura))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ultimaAttLayout.setVerticalGroup(
            ultimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ultimaAttLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(ultimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(ultimaData))
                .addGap(18, 18, 18)
                .addGroup(ultimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ultimaTemperatura))
                .addGap(18, 18, 18)
                .addGroup(ultimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ultimaUmidade)
                    .addComponent(jLabel22))
                .addGap(27, 27, 27)
                .addGroup(ultimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ultimaPressao))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tableRegistros.setBackground(new java.awt.Color(204, 153, 0));
        tableRegistros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        registroTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Temperatura", "Umidade", "Pressão"
            }
        ));
        jScrollPane1.setViewportView(registroTabela);

        removerBotao.setText("Remover");
        removerBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tableRegistrosLayout = new javax.swing.GroupLayout(tableRegistros);
        tableRegistros.setLayout(tableRegistrosLayout);
        tableRegistrosLayout.setHorizontalGroup(
            tableRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tableRegistrosLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(removerBotao)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        tableRegistrosLayout.setVerticalGroup(
            tableRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerBotao)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel28.setText("Número de registros de tempo:");

        totalDeRegistros.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ultimaAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(tableRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dadosTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dadosMedios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(configuracaoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(totalDeRegistros)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadosTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configuracaoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadosMedios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ultimaAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(tableRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalDeRegistros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incluirDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirDadosActionPerformed
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        var data = LocalDate.parse(this.dataDadosTempo.getText(), formatter);
        var temperatura = Double.parseDouble(this.temperaturaDadosTempo.getText());
        var umidade = Double.parseDouble(this.umidadeDadosTempo.getText());
        var pressao = Double.parseDouble(this.pressaoDadosTempo.getText());
        
        this.tempoPresenter.incluirDados(data, temperatura, umidade, pressao);
        
        this.ultimaData.setText(this.tempoPresenter.getUltimoRegistro().getData().format(formatter));
        this.ultimaPressao.setText(this.tempoPresenter.getUltimoRegistro().getPressao().toString());
        this.ultimaTemperatura.setText(this.tempoPresenter.getUltimoRegistro().getTemperatura().toString());
        this.ultimaUmidade.setText(this.tempoPresenter.getUltimoRegistro().getUmidade().toString());
        
        Vector dadosTabela = new Vector();
        dadosTabela.add(this.tempoPresenter.getUltimoRegistro().getData().format(formatter));
        dadosTabela.add(this.tempoPresenter.getUltimoRegistro().getTemperatura().toString());
        dadosTabela.add(this.tempoPresenter.getUltimoRegistro().getUmidade().toString());
        dadosTabela.add(this.tempoPresenter.getUltimoRegistro().getPressao().toString());
        DefaultTableModel model = (DefaultTableModel) registroTabela.getModel();
        model.addRow(dadosTabela);
        
        dataDadosTempo.setText("");
        umidadeDadosTempo.setText("");
        pressaoDadosTempo.setText("");
        temperaturaDadosTempo.setText("");
        
 
        atualizaTotalRegistros();
        atualizaMedia();
    }//GEN-LAST:event_incluirDadosActionPerformed

    private void atualizaMedia(){
        var opcao = this.selecionadorPeriodo.getSelectedIndex();
        this.tempoPresenter.calculaMedia(opcao);
        
        if (opcao == 0){
            this.temperaturaMedia.setText(this.tempoPresenter.getMediaDiaria().getMediaTemperatura().toString());
            this.pressaoMedia.setText(this.tempoPresenter.getMediaDiaria().getMediaPressao().toString());
            this.umidadeMedia.setText(this.tempoPresenter.getMediaDiaria().getMediaUmidade().toString());
            this.numeroDeRegistrosPeriodo.setText(String.valueOf(this.tempoPresenter.getCountRegistros()));
        }
        
        if (opcao == 1){
            this.temperaturaMedia.setText(this.tempoPresenter.getMediaSemanal().getMediaTemperatura().toString());
            this.pressaoMedia.setText(this.tempoPresenter.getMediaSemanal().getMediaPressao().toString());
            this.umidadeMedia.setText(this.tempoPresenter.getMediaSemanal().getMediaUmidade().toString());
            this.numeroDeRegistrosPeriodo.setText(String.valueOf(this.tempoPresenter.getCountRegistros()));
        }
        
        if (opcao == 2){
            this.temperaturaMedia.setText(this.tempoPresenter.getMediaMensal().getMediaTemperatura().toString());
            this.pressaoMedia.setText(this.tempoPresenter.getMediaMensal().getMediaPressao().toString());
            this.umidadeMedia.setText(this.tempoPresenter.getMediaMensal().getMediaUmidade().toString());
            this.numeroDeRegistrosPeriodo.setText(String.valueOf(this.tempoPresenter.getCountRegistros()));
        }
    }
    private void umidadeDadosTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umidadeDadosTempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umidadeDadosTempoActionPerformed

    private void removerBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBotaoActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) registroTabela.getModel();
        var row = registroTabela.getSelectedRow();
        
        this.tempoPresenter.deleteLog(row);
        this.tempoPresenter.deletarDados(row);
        model.removeRow(registroTabela.getSelectedRow());
        atualizaMedia();
        
        atualizaTotalRegistros();
    }//GEN-LAST:event_removerBotaoActionPerformed
    
    private void atualizaTotalRegistros(){
        totalDeRegistros.setText(Integer.toString(this.tempoPresenter.getDados().getDados().size()));
    }
    private void dataDadosTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDadosTempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDadosTempoActionPerformed

    private void selecionadorPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionadorPeriodoActionPerformed
        atualizaMedia();
    }//GEN-LAST:event_selecionadorPeriodoActionPerformed

    private void salvarConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarConfigActionPerformed
        this.tempoPresenter.salvarLog(this.selecionadorPeriodo.getSelectedIndex());
    }//GEN-LAST:event_salvarConfigActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaInicial().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> configSistemaLog;
    private javax.swing.JPanel configuracaoSistema;
    private javax.swing.JPanel dadosMedios;
    private javax.swing.JPanel dadosTempo;
    private javax.swing.JFormattedTextField dataDadosTempo;
    private javax.swing.JButton incluirDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numeroDeRegistrosPeriodo;
    private javax.swing.JTextField pressaoDadosTempo;
    private javax.swing.JLabel pressaoMedia;
    private javax.swing.JTable registroTabela;
    private javax.swing.JButton removerBotao;
    private javax.swing.JButton salvarConfig;
    private javax.swing.JComboBox<String> selecionadorPeriodo;
    private javax.swing.JPanel tableRegistros;
    private javax.swing.JTextField temperaturaDadosTempo;
    private javax.swing.JLabel temperaturaMedia;
    private javax.swing.JPanel title;
    private javax.swing.JLabel totalDeRegistros;
    private javax.swing.JPanel ultimaAtt;
    private javax.swing.JLabel ultimaData;
    private javax.swing.JLabel ultimaPressao;
    private javax.swing.JLabel ultimaTemperatura;
    private javax.swing.JLabel ultimaUmidade;
    private javax.swing.JTextField umidadeDadosTempo;
    private javax.swing.JLabel umidadeMedia;
    // End of variables declaration//GEN-END:variables
}
